/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2.Visual.Formas;

import javax.swing.JOptionPane;
import proyecto2.Visual.Logica.Banco;
import proyecto2.Visual.Logica.SystemBanc;
import proyecto2.Visual.Logica.Usuario;

/**
 *
 * @author zerokull
 */
public class SystemBank extends javax.swing.JFrame {

    /**
     * Creates new form SystemBank
     */
    public SystemBank() {
        initComponents();
        lblUser.setText(SystemBanc.bank.getActivo().getNombre()+" /");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogout = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        btnAddAccount = new javax.swing.JButton();
        btnDepositBalance = new javax.swing.JButton();
        btnRemoveBalance = new javax.swing.JButton();
        btnTransferBalance = new javax.swing.JButton();
        btnRecodInterest = new javax.swing.JButton();
        btnLookAccount = new javax.swing.JButton();
        btnCancelAccount = new javax.swing.JButton();
        btnCreateUser = new javax.swing.JButton();
        btnRecords = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu del Banco");

        lblLogout.setFont(new java.awt.Font("DejaVu Sans Condensed", 3, 12)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(54, 46, 254));
        lblLogout.setText("Cerrar Sesion");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });

        lblUser.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 12)); // NOI18N
        lblUser.setForeground(new java.awt.Color(54, 46, 254));
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUser.setText("jLabel1");

        btnAddAccount.setText("Agregar Cuenta");
        btnAddAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAccountActionPerformed(evt);
            }
        });

        btnDepositBalance.setText("Depositar en cuenta");

        btnRemoveBalance.setText("Retirar de Cuenta");

        btnTransferBalance.setText("Transferencia a Terceros");

        btnRecodInterest.setText("Registrar Intereses");
        btnRecodInterest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecodInterestActionPerformed(evt);
            }
        });

        btnLookAccount.setText("Desactivar cuentas");

        btnCancelAccount.setText("Cancelar Cuenta");

        btnCreateUser.setText("Crear Usuarios");
        btnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUserActionPerformed(evt);
            }
        });

        btnRecords.setText("Reportes");
        btnRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordsActionPerformed(evt);
            }
        });

        btnExit.setText("Salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLogout))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTransferBalance)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddAccount)
                            .addComponent(btnDepositBalance)
                            .addComponent(btnRemoveBalance))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRecodInterest)
                            .addComponent(btnLookAccount)
                            .addComponent(btnCancelAccount))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExit)
                            .addComponent(btnRecords)
                            .addComponent(btnCreateUser))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogout)
                    .addComponent(lblUser))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddAccount)
                    .addComponent(btnRecodInterest)
                    .addComponent(btnCreateUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDepositBalance)
                    .addComponent(btnLookAccount)
                    .addComponent(btnRecords))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoveBalance)
                    .addComponent(btnCancelAccount)
                    .addComponent(btnExit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTransferBalance)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        SystemBanc.bank.logout();
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        SystemBanc.callsMenuBank(11, null, null, null);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnAddAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAccountActionPerformed
        if(!SystemBanc.bank.getActivo().validateTipo(Usuario.LIMITADO)){
            AgregarCuenta nueva = new AgregarCuenta();
            nueva.setVisible(true);
            dispose();   
        }else{
            JOptionPane.showMessageDialog(this, "No Tiene Permiso para agregar cuenta Ingeniero!", "No Tiene Permisos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddAccountActionPerformed

    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
        if(SystemBanc.bank.getActivo().validateTipo(Usuario.ADMINISTRADOR)){
            new CreateUser().setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(this, "No tiene Permisos para Crear Usuarios Ingeniero! ", "Error Crear Usuario", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCreateUserActionPerformed

    private void btnRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordsActionPerformed
        new Records().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRecordsActionPerformed

    private void btnRecodInterestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecodInterestActionPerformed
        new RecordInterest().setVisible(true);
    }//GEN-LAST:event_btnRecodInterestActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemBank().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAccount;
    private javax.swing.JButton btnCancelAccount;
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JButton btnDepositBalance;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLookAccount;
    private javax.swing.JButton btnRecodInterest;
    private javax.swing.JButton btnRecords;
    private javax.swing.JButton btnRemoveBalance;
    private javax.swing.JButton btnTransferBalance;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
}
